---
downloads: ~/.ansible-downloads/

configure_dotfiles: no
configure_sudoers: no
configure_terminal: no
configure_osx: no

dotfiles_repo: https://github.com/ybryan/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/Dropbox/Development/dotfiles
dotfiles_files:
  - .zshrc
  - .tmux.conf
  - .gitconfig
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc

homebrew_installed_packages:
  - ansible 
  - autoconf
  - awscli
  - flake8
  - direnv
  - gcc
  - gettext
  - git
  - go
  - hugo
  - htop
  - jq
  - libevent
  - sqlite
  - mas
  - node
  - nload
  - nvm
  - openssl
  - packer
  - pandoc
  - pipenv
  - postgresql
  - pyenv
  - python
  - readline
  - reattach-to-user-namespace
  - redis
  - rysnc
  - scala
  - sbt
  - ssh-copy-id
  - terraform
  - tmux
  - tree
  - watch
  - wget
  - zsh
  - zsh-completions
  - zsh-syntax-highlighting

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - 1password
  - amazon-workspaces
  - bartender
  - box-sync
  - cyberduck
  - divvy
  - docker
  - dropbox
  - firefox
  - font-source-code-pro
  - google-chrome
  - iterm2
  - java
  - java8
  - karabiner-elements
  - mactex
  - r-app
  - rstudio
  - slack
  - spotify
  - vagrant
  - virtualbox
  - vlc
  - xquartz

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: 
  - { id: 425264550, name: "Kindle (1.23.3)" }
  - { id: 411643860, name: "DaisyDisk (4.6.5.1)" }
  - { id: 507257563, name: "Sip (4.5.2)" }
  - { id: 1295203466, name: "Microsoft Remote Desktop (10.2.3)" }
  - { id: 497799835, name: "Xcode (10.1)" }
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages: []
  # - name: serverless
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A

# Don't use this. System pip will get polluted
pip_packages: []  
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
